RFC0008 - Module system
Draco-lang/Language-suggestions pull request #101
Opened 2022-10-26 08:31 UTC by jakubbinter

Rhis RFC describes the basics of module system, importing and exporting symbols.

2022-10-26 18:43 UTC, LPeter1997 requested changes
As a first draft, this is ok, but very imprecise for a specification. There's a huge lack of explanation of the actual mechanism. Examples are fine, but they should be the "second-line" when explaining.

2022-10-26 18:43 UTC, LPeter1997 commented on Specification/ModuleSystem.md
> +This RFC defines how we split up code to multiple files, export symbols, import symbols and how do we define reusable units of code.
```suggestion
This RFC defines how we split up code to multiple files, export symbols, import symbols and how we define reusable units of code.  
```

2022-10-26 18:43 UTC, LPeter1997 commented on Specification/ModuleSystem.md
> +This RFC defines how we split up code to multiple files, export symbols, import symbols and how do we define reusable units of code.
Some rephrasing should be done to exclude 'we' from the picture. This is specification text.

2022-10-26 18:43 UTC, LPeter1997 commented on Specification/ModuleSystem.md
> +Package is reusable unit of code, which contains one or more modules, it is equivalent to a c# project and we can generate one nuget package from it.
```suggestion
A package is a reusable unit of code, which consists of modules. In C# terminology, it is equivalent to a project that can be distributed as a NuGet package.
```

2022-10-26 18:43 UTC, LPeter1997 commented on Specification/ModuleSystem.md
> +Module is portion of code. Module hierarchy follows the directory structure, meaning that file `bar.draco` in directory `foo` produces module `foo.bar`. Module folders can group their contribution un
You are phrasing it extremely densely, it's hard to grasp.

2022-10-26 18:43 UTC, LPeter1997 commented on Specification/ModuleSystem.md
> +Module is portion of code. Module hierarchy follows the directory structure, meaning that file `bar.draco` in directory `foo` produces module `foo.bar`. Module folders can group their contribution un
An example is nice, but introduce the conceptual words like package, module, module hierarchy more precisely. The example can come after, and definitely graph out the directory structure in a code block, not just in text.

2022-10-26 18:43 UTC, LPeter1997 commented on Specification/ModuleSystem.md
> +Each module is responsible for exporting their own API towards other modules. Any symbol that should be accessible from the outside should be marked for exporting, using the `export` keyword. Symbols
This sentence spans a whopping 3 lines! While it's not particularly a complex one, it's definitely hard to understand as a whole, even on 2nd or 3rd read. I suggest breaking it up.

2022-10-26 18:43 UTC, LPeter1997 commented on Specification/ModuleSystem.md
> +Symbols can also be reexported using the `from` keyword with syntax `from <module name> export <symbol list>` where instead of symbol list we can also use `*` to export everything.
```suggestion
Symbols can also be re-exported using the `from` keyword with syntax `from <module name> export <symbol list>` where instead of symbol list we can also use `*` to export everything.  
```

2022-10-26 18:43 UTC, LPeter1997 commented on Specification/ModuleSystem.md
> +Example of reexporting:
```suggestion
Example of re-exporting:
```

2022-10-28 10:40 UTC, LPeter1997 reviewed
We are getting there! You chose a seriously difficult one to spec out, but I believe it's also very important to get right.

2022-10-28 10:40 UTC, LPeter1997 commented on Specification/ModuleSystem.md
> +A package is a reusable unit of code, which consists of modules. In C# terminology, it is equivalent to a project that can be distributed as a NuGet package. Module is portion of code equivalent to d
> In C# terminology, it is equivalent to a project that can be distributed as a NuGet package

You mention both packages and modules in the previous sentence, it's unclear which one you refer to. You could either state it explicitly or talk about modules later.

2022-10-28 10:40 UTC, LPeter1997 commented on Specification/ModuleSystem.md
> +A package is a reusable unit of code, which consists of modules. In C# terminology, it is equivalent to a project that can be distributed as a NuGet package. Module is portion of code equivalent to d
> Module name is same as name of draco file without file extension, or as folder name.

Here a single example in a sentence would be great. "For example, `math.draco` defines the module named `math`"

2022-10-28 10:40 UTC, LPeter1997 commented on Specification/ModuleSystem.md
> +A package is a reusable unit of code, which consists of modules. In C# terminology, it is equivalent to a project that can be distributed as a NuGet package. Module is portion of code equivalent to d
I'd might tackle the issue of modules in a completely separate section and try to approach it from a hierarchy perspective. Our modules make up a tree hierarchy, it might be easier to explain terminology and elements through that. (we could discuss on the server exactly how)

2022-10-28 10:40 UTC, LPeter1997 commented on Specification/ModuleSystem.md
> +Each module is responsible for exporting their own API towards other modules. Any symbol that should be accessible from the outside must be marked for exporting, using the `export` keyword. Symbols c
> Each module is responsible for exporting their own API towards other modules.

This is a key observation, really nice!

2022-10-28 10:40 UTC, LPeter1997 commented on Specification/ModuleSystem.md
> +Symbols can be accessed through their fully qualified name, but importing into local scope can be done with the `import` statement, that has syntax `from <module name> import <symbol list>` where sym
> Symbols can be accessed through their fully qualified name

That's not 100% correct, they can only be referenced through the qualified name if the module path has been fully exported down the line, meaning that in `x::y::z::foo()`, `foo` was exported in `z`, `z` was exported in `y`, `y` was exported in `x` and `x` was exported in the top-level module.

2022-10-31 10:37 UTC, LPeter1997 reviewed
Way better than the first iteration, we are getting to an almost spec-like stage.

2022-10-31 10:37 UTC, LPeter1997 commented on Specification/ModuleSystem.md
> +A package is a reusable unit of code, which consists of modules. In C# terminology, package is equivalent to a project that can be distributed as a NuGet package. Module is portion of code equivalent
> Module is portion of code equivalent to draco file

This is imprecise, a file can actually define multiple modules by the issue currently (yes you expand on this later but we shouldn't start the specs with an imprecision like this). Modules should be explained as the building blocks of packages, that provide or hide pieces functionality to make up the package or something.

2022-10-31 10:37 UTC, LPeter1997 commented on Specification/ModuleSystem.md
> +A package is a reusable unit of code, which consists of modules. In C# terminology, package is equivalent to a project that can be distributed as a NuGet package. Module is portion of code equivalent
> Module is portion

> Module name

I'm missing a couple of articles all around. When in singular, it reads more natural to start with an article. "A module", "The module", ...

2022-10-31 10:37 UTC, LPeter1997 commented on Specification/ModuleSystem.md
> +A package is a reusable unit of code, which consists of modules. In C# terminology, package is equivalent to a project that can be distributed as a NuGet package. Module is portion of code equivalent
> Modules declared like this will become submodule of the module they were declared in

Yes, but the modules declared within the directory are also submodules. I know you expand on this later, but this is why I suggested approaching all of this from a standpoint of hierarchy. You are duplicating a lot of knowledge between nesting modules within a file and nesting within folders.

2022-10-31 10:37 UTC, LPeter1997 commented on Specification/ModuleSystem.md
> +```
Let's come up with a more practical example for a specs. The one later is really good!

2022-10-31 10:37 UTC, LPeter1997 commented on Specification/ModuleSystem.md
> +**Note**: the module is only visible by its parent module before export, meaning that this is only valid at the module parent.
This sentence is highly ambiguous and hints that it won't be visible after export.

2022-10-31 10:37 UTC, LPeter1997 commented on Specification/ModuleSystem.md
> +Symbols can also be re-exported using the `from` keyword with syntax `from <module name> export <symbol list>` where instead of symbol list we can also use `*` to export everything.
I'm missing an explanation on what re-exporting actually is.

2022-11-03 17:54 UTC, Kuinox commented on Specification/ModuleSystem.md
> +A package is a reusable unit of code, which consists of modules. In C# terminology, package is equivalent to a project that can be distributed as a NuGet package. Modules are building blocks of packa
Break the line more often, this line fill more than my gigantic smartphone screen.
Adding space make text more readable too.  

About projects:
A nuget package can contains multiples DLLs
A DLL can be the product of multiples projects (source imports is common in some corners of .NET).

2022-11-20 00:34 UTC, Kuinox reviewed
Incomplete review for now.

2022-11-20 00:34 UTC, Kuinox commented on Specification/ModuleSystem.md
> +from constants export { GravityConstant as G, * };
I have an issue with that, there is a lot of ambiguity about what it is happening here.  
For example, is GravityConstant exported two time, if not, why ?
This specs here doesn't specify this behavior too.

2022-11-20 00:34 UTC, Kuinox commented on Specification/ModuleSystem.md
> +A package is a reusable unit of code, which consists of modules. In C# terminology, package is equivalent to a project. Modules are building blocks of packages, they provide or hide pieces functional
Same comment than on the other specs, the text is too dense, give more room for the reader to breath, try to start sentences on a new line more often.  
At least here the sentence are shorts enough, you only need to change the spacing.

2022-11-20 00:34 UTC, Kuinox commented on Specification/ModuleSystem.md
> +A package is a reusable unit of code, which consists of modules. In C# terminology, package is equivalent to a project. Modules are building blocks of packages, they provide or hide pieces functional
> A package is a reusable unit of code

Doesn't mean a lot IMO, and may also be wrong. Does a console app be a package ? If yes, the code here is not intended to be reusable.

2022-11-20 00:34 UTC, Kuinox commented on Specification/ModuleSystem.md
> +A package is a reusable unit of code, which consists of modules. In C# terminology, package is equivalent to a project. Modules are building blocks of packages, they provide or hide pieces functional
> they provide or hide

replace `provide` with `expose`

2022-12-04 09:15 UTC, merged